python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
python cluster_test.py -S 10 -s extended -d numeric -c gmm -V n_components
